import sendEmail from "./mailer";
import {Order} from "../AWS/orders"


/**
 * Send an "order received" confirmation email to a customer.
 * @param customerEmail - Email address of the customer
 * @param orderId - Unique order ID
 */
export async function sendOrderReceivedEmail(
  customerEmail: string,
  orderId: string
): Promise<void> {
  const subject = `✅ Order Confirmation #${orderId}`;
  const text = `Hello,

Thank you for your purchase! 🎉
We’ve received your order (#${orderId}) and it’s now being processed.

You’ll get another email once your order has shipped.

If you have any questions, just reply to this email and we’ll be happy to help.

- The mRehab Team
`;

  const html = `
    <div style="font-family: Arial, sans-serif; line-height:1.6; color:#333;">
      <h2 style="color:#2a6df4;">Thank you for your order! 🎉</h2>
      <p>We’ve received your order <strong>#${orderId}</strong> and it is now being processed.</p>
      <p>You’ll receive another email once your order has shipped.</p>
      
      <div style="margin:20px 0; padding:12px; background:#f9f9f9; border-radius:6px;">
        <p style="margin:0; font-size:14px; color:#555;">
          <strong>Order ID:</strong> ${orderId}<br/>
          <strong>Status:</strong> Processing
        </p>
      </div>

      <p>If you have any questions, just reply to this email and we’ll be happy to help.</p>
      <p style="margin-top:24px;">— The <strong>mRehab</strong> Team</p>

      <hr />
      <p style="font-size:12px; color:#777;">
        This is a confirmation that we received your order. You’ll be notified again when it ships.
      </p>
    </div>
  `;

  await sendEmail(
    "jsmith720847@gmail.com", // must be verified SES identity
    // customerEmail,            // use real customer email in production
    "jsmith720847@gmail.com", // must be verified SES identity
    subject,
    text,
    html
  );
}


/**
 * Send an internal notification email to the fulfillment team with full order details.
 * @param order - The order object
 */
export async function sendInternalOrderNotification(order: Order): Promise<void> {
  const subject = `📦 New Order Received - #${order.id}`;

  const amountDisplay = order.amount
    ? `${(order.amount / 100).toFixed(2)} ${order.currency?.toUpperCase() || ""}`
    : "N/A";

  const text = `Team,

A new order has been placed and requires fulfillment.

Order ID: ${order.id}
Customer Email: ${order.email || "N/A"}
Phone: ${order.phone || "N/A"}
Device: ${order.device || "N/A"}
Amount: ${amountDisplay}
Payment Status: ${order.status}
Shipping Status: ${order.shippingStatus}
Created At: ${order.createdAt}

Shipping Address:
${order.shippingAddress || "N/A"}

Please prepare the package and arrange shipping.

- Automated Notification (mRehab System)`;

  const html = `
    <div style="font-family: Arial, sans-serif; line-height:1.6; color:#333;">
      <h2 style="color:#2a6df4;">📦 New Order Alert</h2>
      <p>A new order has been placed and requires fulfillment. Below are the details:</p>

      <div style="margin:20px 0; padding:16px; background:#f9f9f9; border-radius:8px;">
        <p style="margin:0; font-size:14px; color:#333;">
          <strong>Order ID:</strong> ${order.id}<br/>
          <strong>Created At:</strong> ${new Date(order.createdAt).toLocaleString()}<br/>
          <strong>Amount:</strong> ${amountDisplay}<br/>
          <strong>Payment Status:</strong> ${order.status}<br/>
          <strong>Shipping Status:</strong> ${order.shippingStatus}
        </p>
      </div>

      <h3>Customer Information</h3>
      <p style="margin:0; font-size:14px; color:#555;">
        <strong>Name / Email:</strong> ${order.email || "N/A"}<br/>
        <strong>Phone:</strong> ${order.phone || "N/A"}<br/>
        <strong>Device Ordered:</strong> ${order.device || "N/A"}
      </p>

      <h3 style="margin-top:20px;">Shipping Address</h3>
      <p style="margin:0; font-size:14px; color:#555;">
        ${order.shippingAddress || "N/A"}
      </p>

      ${
        order.shippingAddressRaw
          ? `<pre style="font-size:12px; background:#f4f4f4; padding:10px; border-radius:6px; overflow-x:auto;">
${JSON.stringify(order.shippingAddressRaw, null, 2)}
</pre>`
          : ""
      }

      <hr />
      <p style="font-size:12px; color:#777;">
        This email was automatically generated by the mRehab system. Fulfillment can proceed based on the above details.
      </p>
    </div>
  `;

  await sendEmail(
    "jsmith720847@gmail.com", // must be a verified SES identity
    "jsmith720847@gmail.com", // replace with warehouse/fulfillment team email in prod
    subject,
    text,
    html
  );
}